version: '3.2'
services:        
  grafana:
    image: grafana/grafana:9.3.8
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - 3000:3000
    user: "${UID}:${GID}"  
    volumes:
      - ./data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning
    networks:
      - service-network
networks:
 service-network:
   name: dev
   driver: bridge
