version: '3.4'

services:
  influxdb:
    image: influxdb:1.8
    hostname: influxdb-1-8
    networks:
      - service-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  grafana:
    image: grafana/grafana:9.3.8
    networks:
      - service-network
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning

  k6:
    image: grafana/k6
    networks:
      - service-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb-1-8:8086/k6
    volumes:
      - ./scripts:/scripts

networks:
 service-network:
   name: dev
   driver: bridge

