version: '3.4'

services:
  influxdb:
    image: influxdb:1.8
    hostname: influxdb-1-8
    networks:
      - service-network
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
  k6:
    image: grafana/k6
    networks:
      - service-network
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb-1-8:8086/k6
    volumes:
      - ./scripts:/scripts

networks:
 service-network:
   name: dev
   driver: bridge

