scrape_configs:
- job_name: main
  scrape_interval: 5s
  static_configs:
  - targets:
    - social-net:8080
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:9092    