version: "3"

networks:
    graylog:
        driver: bridge

services:
    mongo:
        image: mongo:3
        networks:
        - graylog
    elasticsearch:
        image: blacktop/elasticsearch:6.8.10
        environment:
        - http.host=0.0.0.0
        - transport.host=localhost
        - network.host=0.0.0.0
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
              soft: -1
              hard: -1
        deploy:
          resources:
              limits:
                memory: 2g
        networks:
        - graylog

    graylog:
        image: graylog/graylog:3.3
        hostname: graylog-3-3
        environment:
        - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
        - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - GRAYLOG_HTTP_EXTERNAL_URI=http://riva.local:9000/
        networks:
        - graylog
        depends_on:
        - mongo
        - elasticsearch
        ports:
        # Graylog web interface and REST API
        - 9000:9000
        # Syslog TCP
        - 1514:1514
        # Syslog UDP
        - 1514:1514/udp
        # GELF TCP
        - 12201:12201
        # GELF UDP
        - 12201:12201/udp